### ISSUE TITLE
non-docker support - buildah and skopeo or just podman

### ISSUE THREAD

**Issue by ikke-t** [sebgroup/repo-operator#3]
Hi,

congrats and thanks for opening this operator for public! I took a quick look and would like to grab the honor of doing the very first request for enhancement (RFE).

I quickly took a look how you build the operator. I see this is still bound to Docker. I'd like to raise a use case:

"**As a RHEL8 or OCP4 user, I want to be able to build the operator without Docker.**"

Neither systems won't utilise Docker any more, but have moved further to libpod components buildah, podman and skopeo (https://github.com/containers/libpod).

This would require small changes. The Makefile uses docker to do the build, as well as for the image push. There should be:

1. check if system has libpod tools (podman) or docker
2. put the tool names into variables. If using just podman, the existing arguments should be compatible.

Podman utilises the other libpod tools in background, so likely no reason to use buildah or skopeo directly. Only if one would want to drop the whole Dockerfile concept and go fully to buildah. For compatibility, probably better to not go that far at first.

Here is quick tutorial how to use podman: https://developers.redhat.com/blog/2019/02/21/podman-and-buildah-for-docker-users/

BR,
Ilkka Tengvall

**Comment by ikke-t** [comment]
Change would be along the lines of this, I don't now have time to figure out how Makefile magic works with ifs....

```
diff --git a/Makefile b/Makefile
index 4fdcdac..2436e15 100644
--- a/Makefile
+++ b/Makefile
@@ -11,6 +11,14 @@ else
 GOBIN=$(shell go env GOBIN)
 endif
 
+# some if magick here for finding out if podman exists 
+CONTAINER_TOOL=$(shell which podman)
+# else some if magick here for finding out if podman exists 
+#  CONTAINER_TOOL=$(shell which docker)
+#else
+#  $(error "No container build tools in path")
+#endif
+
 all: manager
 
 # Run tests
@@ -51,12 +59,12 @@ generate: controller-gen
        $(CONTROLLER_GEN) object:headerFile=./hack/boilerplate.go.txt paths="./..."
 
 # Build the docker image
-docker-build: test
-       docker build . -t ${IMG}
+container-build: test
+       ${CONTAINER_TOOL} build . -t ${IMG}
 
 # Push the docker image
-docker-push:
-       docker push ${IMG}
+container-push:
+       ${CONTAINER_TOOL} push ${IMG}
 
 # find or download controller-gen
 # download controller-gen if necessary
```

**Comment by chetansha256** [comment]
@ikke-t yes ..that could be a good improvement to have support for something other than docker. do you think you can create a PR with this?

**Comment by ikke-t** [comment]
I almost did already. I just fumbled in Makefile ifs, I am not handy with the language. By quick try this does not work, do you know what's the error?

```
diff --git a/Makefile b/Makefile
index 4fdcdac..0c70601 100644
--- a/Makefile
+++ b/Makefile
@@ -11,6 +11,14 @@ else
 GOBIN=$(shell go env GOBIN)
 endif
 
+ifeq (,$(shell which podman))
+  CONTAINER_TOOL=$(shell which podman)
+else ifeq (,$(shell which docker))
+  CONTAINER_TOOL=$(shell which docker)
+else
+  $(error "No container build tools in path")
+endif
+
 all: manager
 
 # Run tests
```

**Comment by ikke-t** [comment]
It does not set anything to CONTAINER_TOOL, even though I do have /usr/bin/podman

**Comment by msjostrom** [comment]
Two things; you open two ifs so you need two endifs and you've inverted the logic, if (which podman) equals empty string, you set the tool to podman, it should be the other way around:

```
ifeq (,$(shell which podman))
  CONTAINER_TOOL=$(shell which docker)
  else
  ifeq (,$(shell which docker))
    CONTAINER_TOOL=$(shell which podman)
    else
    $(error "No container build tools in path")
  endif
endif
```
